[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "taad-smc-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Will Zhang", email = "willwz@gmail.com" }]
requires-python = ">=3.12"
dependencies = ["taad-smc-io", "taad-smc-prep"]

[tool.uv.build-backend]
module-name = "taad_smc"
namespace = true
